pdf-simple-sign
===============

'pdf-simple-sign' is a simple PDF signer intended for documents produced by
the Cairo library, GNU troff, ImageMagick, or similar.

I don't aim to extend the functionality any further.  The project is fairly
self-contained and it should be easy to grasp and change to suit to your needs.

Documentation
-------------
See the link:pdf-simple-sign.adoc[man page] for information about usage.
The rest of this README will concern itself with externalities.

Building
--------
Build dependencies: Meson, Asciidoctor, a C++11 compiler, pkg-config +
Runtime dependencies: libcrypto (OpenSSL 1.1 API)

 $ git clone https://git.janouch.name/p/pdf-simple-sign.git
 $ cd pdf-simple-sign
 $ meson builddir
 $ cd builddir
 $ ninja

In addition to the C++ version, also included is a native Go port:

 $ go get janouch.name/pdf-simple-sign/cmd/pdf-simple-sign

Contributing and Support
------------------------
Use https://git.janouch.name/p/pdf-simple-sign to report bugs, request features,
or submit pull requests.  `git send-email` is tolerated.  If you want to discuss
the project, feel free to join me at ircs://irc.janouch.name, channel #dev.

Bitcoin donations are accepted at: 12r5uEWEgcHC46xd64tt3hHt9EUvYYDHe9

License
-------
This software is released under the terms of the 0BSD license, the text of which
is included within the package along with the list of authors.
